**State the Hypotheses:**

A statistical technique called hypothesis testing is used to determine if a certain claim (hypothesis) about a population is sufficiently supported by the evidence in a sample of data. It helps in determining whether there is a substantial difference between the observed data and what we would anticipate given a particular assumption.



**Compute the Chi-Square Statistic:**

In [2]:
#step1: import libaries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
df=pd.read_csv('/content/CHi-square assignment - Sheet1.csv')
df


Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70
5             Total               240          360    600

In [4]:
#step:2 some exploratory data analysis
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Satisfaction      6 non-null      object
 1   Smart Thermostat  6 non-null      int64 
 2   Smart Light       6 non-null      int64 
 3   Total             6 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 320.0+ bytes


In [5]:
df.describe()

Smart Thermostat  Smart Light       Total
count          6.000000     6.000000    6.000000
mean          80.000000   120.000000  200.000000
std           81.240384   119.331471  200.299775
min           20.000000    50.000000   70.000000
25%           35.000000    55.000000   90.000000
50%           55.000000    80.000000  135.000000
75%           75.000000    97.500000  172.500000
max          240.000000   360.000000  600.000000

In [6]:
#step 3:we are trying to find the relation ship between smoker and gender
dataset_table=pd.crosstab(df['Smart Thermostat'],df['Smart Light'])
dataset_table

Smart Light       50   70   90   100  360
Smart Thermostat                         
20                  1    0    0    0    0
30                  1    0    0    0    0
50                  0    1    0    0    0
60                  0    0    1    0    0
80                  0    0    0    1    0
240                 0    0    0    0    1

In [7]:
#step 4 : observed value
observed_values=dataset_table.values
observed_values

array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [9]:
#step:5=import chiz contugency table
import scipy.stats as stats
import numpy as np
from  scipy.stats import chi2_contingency
val=stats.chi2_contingency(dataset_table)
val
#expected frequency =(row total*column total)/n

Chi2ContingencyResult(statistic=24.000000000000007, pvalue=0.2423921616705121, dof=20, expected_freq=array([[0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667]]))

In [10]:
expected_values=val[3]
expected_values

array([[0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667]])

In [11]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
alpha=0.05
ddof

1

In [12]:
#formula for chi2 (xi=(o-e)^2/e))
#(x=((o-e)**2)/e)
#** indicates exponetial to the power of 2
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])
chi_square
# observed value
#expected value

array([4., 5., 5., 5., 5.])

In [13]:
chi_square_statistic=chi_square[0]+chi_square[1]
#2*2 matrix,row(0) and row(1)
chi_square_statistic

9.000000000000004

In [14]:
#percent point function(inverse of cdf)
critical_value=chi2.ppf(q=1-alpha,df=ddof)
critical_value

3.841458820694124

In [15]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
p_value
#cumulative distribution function

0.002699796063260207

**Make a Decision:**

In [16]:
if chi_square_statistic>=critical_value:
  print("reject H0 ,There is a relationship between 2 categorical variables")
else:
   print("reject H0 ,There is a  no relationship between 2 categorical variables")

reject H0 ,There is a relationship between 2 categorical variables


In [17]:
if p_value<=critical_value:
   print("reject H0 ,There is a relationship between 2 categorical variables")
else:
   print("reject H0 ,There is a  no relationship between 2 categorical variables")

reject H0 ,There is a relationship between 2 categorical variables
